package com.zj.zhijue.glasses.greendao.msdao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zj.zhijue.greendao.greendaobean.CommonFeedBackBleDataDBBean;
import com.zj.zhijue.greendao.greendaobean.FirstBean;
import com.zj.zhijue.greendao.greendaobean.InterveneFeedBackBleDataDBBean;
import com.zj.zhijue.greendao.greendaobean.ReviewDataEyeSightDBBean;
import com.zj.zhijue.greendao.greendaobean.RunParamsBleDataDBBean;
import com.zj.zhijue.greendao.greendaobean.UserInfoDBBean;
import com.zj.zhijue.greendao.greendaobean.UserInfoTrainTimeDBBean;
import com.zj.zhijue.greendao.greendaobean.UserSignInDBBean;

import com.zj.zhijue.glasses.greendao.msdao.CommonFeedBackBleDataDBBeanDao;
import com.zj.zhijue.glasses.greendao.msdao.FirstBeanDao;
import com.zj.zhijue.glasses.greendao.msdao.InterveneFeedBackBleDataDBBeanDao;
import com.zj.zhijue.glasses.greendao.msdao.ReviewDataEyeSightDBBeanDao;
import com.zj.zhijue.glasses.greendao.msdao.RunParamsBleDataDBBeanDao;
import com.zj.zhijue.glasses.greendao.msdao.UserInfoDBBeanDao;
import com.zj.zhijue.glasses.greendao.msdao.UserInfoTrainTimeDBBeanDao;
import com.zj.zhijue.glasses.greendao.msdao.UserSignInDBBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commonFeedBackBleDataDBBeanDaoConfig;
    private final DaoConfig firstBeanDaoConfig;
    private final DaoConfig interveneFeedBackBleDataDBBeanDaoConfig;
    private final DaoConfig reviewDataEyeSightDBBeanDaoConfig;
    private final DaoConfig runParamsBleDataDBBeanDaoConfig;
    private final DaoConfig userInfoDBBeanDaoConfig;
    private final DaoConfig userInfoTrainTimeDBBeanDaoConfig;
    private final DaoConfig userSignInDBBeanDaoConfig;

    private final CommonFeedBackBleDataDBBeanDao commonFeedBackBleDataDBBeanDao;
    private final FirstBeanDao firstBeanDao;
    private final InterveneFeedBackBleDataDBBeanDao interveneFeedBackBleDataDBBeanDao;
    private final ReviewDataEyeSightDBBeanDao reviewDataEyeSightDBBeanDao;
    private final RunParamsBleDataDBBeanDao runParamsBleDataDBBeanDao;
    private final UserInfoDBBeanDao userInfoDBBeanDao;
    private final UserInfoTrainTimeDBBeanDao userInfoTrainTimeDBBeanDao;
    private final UserSignInDBBeanDao userSignInDBBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commonFeedBackBleDataDBBeanDaoConfig = daoConfigMap.get(CommonFeedBackBleDataDBBeanDao.class).clone();
        commonFeedBackBleDataDBBeanDaoConfig.initIdentityScope(type);

        firstBeanDaoConfig = daoConfigMap.get(FirstBeanDao.class).clone();
        firstBeanDaoConfig.initIdentityScope(type);

        interveneFeedBackBleDataDBBeanDaoConfig = daoConfigMap.get(InterveneFeedBackBleDataDBBeanDao.class).clone();
        interveneFeedBackBleDataDBBeanDaoConfig.initIdentityScope(type);

        reviewDataEyeSightDBBeanDaoConfig = daoConfigMap.get(ReviewDataEyeSightDBBeanDao.class).clone();
        reviewDataEyeSightDBBeanDaoConfig.initIdentityScope(type);

        runParamsBleDataDBBeanDaoConfig = daoConfigMap.get(RunParamsBleDataDBBeanDao.class).clone();
        runParamsBleDataDBBeanDaoConfig.initIdentityScope(type);

        userInfoDBBeanDaoConfig = daoConfigMap.get(UserInfoDBBeanDao.class).clone();
        userInfoDBBeanDaoConfig.initIdentityScope(type);

        userInfoTrainTimeDBBeanDaoConfig = daoConfigMap.get(UserInfoTrainTimeDBBeanDao.class).clone();
        userInfoTrainTimeDBBeanDaoConfig.initIdentityScope(type);

        userSignInDBBeanDaoConfig = daoConfigMap.get(UserSignInDBBeanDao.class).clone();
        userSignInDBBeanDaoConfig.initIdentityScope(type);

        commonFeedBackBleDataDBBeanDao = new CommonFeedBackBleDataDBBeanDao(commonFeedBackBleDataDBBeanDaoConfig, this);
        firstBeanDao = new FirstBeanDao(firstBeanDaoConfig, this);
        interveneFeedBackBleDataDBBeanDao = new InterveneFeedBackBleDataDBBeanDao(interveneFeedBackBleDataDBBeanDaoConfig, this);
        reviewDataEyeSightDBBeanDao = new ReviewDataEyeSightDBBeanDao(reviewDataEyeSightDBBeanDaoConfig, this);
        runParamsBleDataDBBeanDao = new RunParamsBleDataDBBeanDao(runParamsBleDataDBBeanDaoConfig, this);
        userInfoDBBeanDao = new UserInfoDBBeanDao(userInfoDBBeanDaoConfig, this);
        userInfoTrainTimeDBBeanDao = new UserInfoTrainTimeDBBeanDao(userInfoTrainTimeDBBeanDaoConfig, this);
        userSignInDBBeanDao = new UserSignInDBBeanDao(userSignInDBBeanDaoConfig, this);

        registerDao(CommonFeedBackBleDataDBBean.class, commonFeedBackBleDataDBBeanDao);
        registerDao(FirstBean.class, firstBeanDao);
        registerDao(InterveneFeedBackBleDataDBBean.class, interveneFeedBackBleDataDBBeanDao);
        registerDao(ReviewDataEyeSightDBBean.class, reviewDataEyeSightDBBeanDao);
        registerDao(RunParamsBleDataDBBean.class, runParamsBleDataDBBeanDao);
        registerDao(UserInfoDBBean.class, userInfoDBBeanDao);
        registerDao(UserInfoTrainTimeDBBean.class, userInfoTrainTimeDBBeanDao);
        registerDao(UserSignInDBBean.class, userSignInDBBeanDao);
    }
    
    public void clear() {
        commonFeedBackBleDataDBBeanDaoConfig.clearIdentityScope();
        firstBeanDaoConfig.clearIdentityScope();
        interveneFeedBackBleDataDBBeanDaoConfig.clearIdentityScope();
        reviewDataEyeSightDBBeanDaoConfig.clearIdentityScope();
        runParamsBleDataDBBeanDaoConfig.clearIdentityScope();
        userInfoDBBeanDaoConfig.clearIdentityScope();
        userInfoTrainTimeDBBeanDaoConfig.clearIdentityScope();
        userSignInDBBeanDaoConfig.clearIdentityScope();
    }

    public CommonFeedBackBleDataDBBeanDao getCommonFeedBackBleDataDBBeanDao() {
        return commonFeedBackBleDataDBBeanDao;
    }

    public FirstBeanDao getFirstBeanDao() {
        return firstBeanDao;
    }

    public InterveneFeedBackBleDataDBBeanDao getInterveneFeedBackBleDataDBBeanDao() {
        return interveneFeedBackBleDataDBBeanDao;
    }

    public ReviewDataEyeSightDBBeanDao getReviewDataEyeSightDBBeanDao() {
        return reviewDataEyeSightDBBeanDao;
    }

    public RunParamsBleDataDBBeanDao getRunParamsBleDataDBBeanDao() {
        return runParamsBleDataDBBeanDao;
    }

    public UserInfoDBBeanDao getUserInfoDBBeanDao() {
        return userInfoDBBeanDao;
    }

    public UserInfoTrainTimeDBBeanDao getUserInfoTrainTimeDBBeanDao() {
        return userInfoTrainTimeDBBeanDao;
    }

    public UserSignInDBBeanDao getUserSignInDBBeanDao() {
        return userSignInDBBeanDao;
    }

}
